/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      typography: (theme) => ({
        DEFAULT: {
          css: {
            hr: {
              borderColor: "var(--color-primary)",
              marginTop: "calc(var(--spacing) * 1)",
              marginBottom: "calc(var(--spacing) * 1)",
            },
            blockquote: {
              padding: "calc(var(--spacing) * 4)",
              fontStyle: "normal",
            },
            "blockquote cite": {
              marginTop: "calc(var(--spacing) * 2)",
              fontSize: "var(--text-sm)",
              textAlign: "right",
              display: "block",
              fontStyle: "normal",
            },
            "blockquote cite::before": {
              content: '"—"',
              marginRight: "calc(var(--spacing) * 1)",
            },
            "samp, code:not(pre code)": {
              fontWeight: theme("fontWeight.normal"),
              fontSize: "var(--text-sm) !important",
              border: "var(--color-border)",
              borderStyle: "solid",
              borderRadius: theme("borderRadius.md"),
              padding: "calc(var(--spacing) * 1) calc(var(--spacing) * 2)",
              margin: "0 calc(var(--spacing) * 0.25)",
              backgroundColor: "var(--color-card)",
            },
            "code::before": {
              content: '""',
            },
            "code::after": {
              content: '""',
            },
            pre: {
              backgroundColor: "var(--color-card)",
              border: "var(--color-border)",
              borderStyle: "solid",
              overflowX: "auto",
              maxWidth: "100%",
              lineHeight: "calc(var(--spacing) * 5) !important",
            },
            table: {
              width: "100% !important",
              minWidth: "100% !important",
              maxWidth: "100% !important",
              tableLayout: "auto",
              display: "block",
              overflowX: "auto",
              whiteSpace: "nowrap",
              padding: "calc(var(--spacing) * 2)",
              // Always show scrollbar
              scrollbarWidth: "thin",
              scrollbarColor: "var(--color-border) transparent",
            },
            a: {
              fontWeight: theme("fontWeight.normal"),
              color: "var(--color-foreground)",
              textDecoration: "underline",
              textUnderlineOffset: "calc(var(--spacing) * 1)",
              textDecorationThickness: "calc(var(--spacing) * 0.25)",
              textDecorationColor: "var(--color-border)",
              "&:hover": {
                textDecorationColor: "var(--color-primary)",
              },
            },
            mark: {
              background: "var(--color-secondary)",
              color: "var(--color-secondary-foreground)",
              padding: "calc(var(--spacing) * 1) calc(var(--spacing) * 2)",
              margin: "0 calc(var(--spacing) * 0.25)",
            },
            ".callout": {
              borderTop: "var(--color-border)",
              borderBottom: "var(--color-border)",
              borderStyle: "solid",
              padding: "calc(var(--spacing) * 4)",
              backgroundColor: "var(--color-card)",
            },
          },
        },
        shadcn: {
          css: {
            "--tw-prose-body": "var(--color-foreground)",
            "--tw-prose-headings": "var(--color-foreground)",
            "--tw-prose-lead": "var(--color-foreground)",
            "--tw-prose-links": "var(--color-border)",
            "--tw-prose-bold": "var(--color-foreground)",
            "--tw-prose-counters": "var(--color-primary)",
            "--tw-prose-bullets": "var(--color-primary)",
            "--tw-prose-hr": "var(--color-primary)",
            "--tw-prose-quotes": "var(--color-foreground)",
            "--tw-prose-quote-borders": "var(--color-foreground)",
            "--tw-prose-captions": "var(--color-foreground)",
            "--tw-prose-code": "var(--color-foreground)",
            "--tw-prose-pre-code": "var(--color-foreground)",
            "--tw-prose-pre-bg": "var(--color-background)",
            "--tw-prose-th-borders": "var(--color-border)",
            "--tw-prose-td-borders": "var(--color-border)",
            "--tw-prose-invert-body": "var(--color-foreground)",
            "--tw-prose-invert-headings": "var(--color-foreground)",
            "--tw-prose-invert-lead": "var(--color-background)",
            "--tw-prose-invert-links": "var(--color-foreground)",
            "--tw-prose-invert-bold": "var(--color-foreground)",
            "--tw-prose-invert-counters": "var(--color-primary)",
            "--tw-prose-invert-bullets": "var(--color-primary)",
            "--tw-prose-invert-hr": "var(--color-primary)",
            "--tw-prose-invert-quotes": "var(--color-foreground)",
            "--tw-prose-invert-quote-borders": "var(--color-foreground)",
            "--tw-prose-invert-captions": "var(--color-foreground)",
            "--tw-prose-invert-code": "var(--color-foreground)",
            "--tw-prose-invert-pre-code": "var(--color-foreground)",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "var(--color-border)",
            "--tw-prose-invert-td-borders": "var(--color-border)",
          },
        },
      }),
    },
  },
};
