import type { ThemePreset } from "../theme-types";

export const defaultGray: ThemePreset = {
  label: "Default Gray",
  styles: {
    light: {
      background: "#ffffff",
      foreground: "#030712",
      card: "#ffffff",
      "card-foreground": "#030712",
      popover: "#ffffff",
      "popover-foreground": "#030712",
      primary: "#101828",
      "primary-foreground": "#f9fafb",
      secondary: "#f3f4f6",
      "secondary-foreground": "#101828",
      muted: "#f3f4f6",
      "muted-foreground": "#6a7282",
      accent: "#f3f4f6",
      "accent-foreground": "#101828",
      destructive: "#e7000b",
      "destructive-foreground": "",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#99a1af",
      "chart-1": "#f54900",
      "chart-2": "#009689",
      "chart-3": "#104e64",
      "chart-4": "#ffb900",
      "chart-5": "#fe9a00",
      radius: "0.625rem",
      sidebar: "#f9fafb",
      "sidebar-foreground": "#030712",
      "sidebar-primary": "#101828",
      "sidebar-primary-foreground": "#f9fafb",
      "sidebar-accent": "#f3f4f6",
      "sidebar-accent-foreground": "#101828",
      "sidebar-border": "#e5e7eb",
      "sidebar-ring": "#99a1af",
      "font-sans":
        "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      "font-serif":
        "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
      "font-mono":
        "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    },
    dark: {
      background: "#030712",
      foreground: "#f9fafb",
      card: "#101828",
      "card-foreground": "#f9fafb",
      popover: "#101828",
      "popover-foreground": "#f9fafb",
      primary: "#e5e7eb",
      "primary-foreground": "#101828",
      secondary: "#1e2939",
      "secondary-foreground": "#f9fafb",
      muted: "#1e2939",
      "muted-foreground": "#99a1af",
      accent: "#1e2939",
      "accent-foreground": "#f9fafb",
      destructive: "#ff6467",
      "destructive-foreground": "",
      border: "#ffffff",
      input: "#ffffff",
      ring: "#6a7282",
      "chart-1": "#1447e6",
      "chart-2": "#00bc7d",
      "chart-3": "#fe9a00",
      "chart-4": "#ad46ff",
      "chart-5": "#ff2056",
      radius: "",
      sidebar: "#101828",
      "sidebar-foreground": "#f9fafb",
      "sidebar-primary": "#1447e6",
      "sidebar-primary-foreground": "#f9fafb",
      "sidebar-accent": "#1e2939",
      "sidebar-accent-foreground": "#f9fafb",
      "sidebar-border": "#ffffff",
      "sidebar-ring": "#6a7282",
    },
  },
};
