import type { ThemePreset } from "@/types/theme-types";

export const defaultSlate: ThemePreset = {
  label: "Default Slate",
  styles: {
    light: {
      background: "#ffffff",
      foreground: "#020618",
      card: "#ffffff",
      "card-foreground": "#020618",
      popover: "#ffffff",
      "popover-foreground": "#020618",
      primary: "#0f172b",
      "primary-foreground": "#f8fafc",
      secondary: "#f1f5f9",
      "secondary-foreground": "#0f172b",
      muted: "#f1f5f9",
      "muted-foreground": "#62748e",
      accent: "#f1f5f9",
      "accent-foreground": "#0f172b",
      destructive: "#e7000b",
      "destructive-foreground": "",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#90a1b9",
      "chart-1": "#f54900",
      "chart-2": "#009689",
      "chart-3": "#104e64",
      "chart-4": "#ffb900",
      "chart-5": "#fe9a00",
      radius: "0.625rem",
      sidebar: "#f8fafc",
      "sidebar-foreground": "#020618",
      "sidebar-primary": "#0f172b",
      "sidebar-primary-foreground": "#f8fafc",
      "sidebar-accent": "#f1f5f9",
      "sidebar-accent-foreground": "#0f172b",
      "sidebar-border": "#e2e8f0",
      "sidebar-ring": "#90a1b9",
      "font-sans":
        "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      "font-serif":
        "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
      "font-mono":
        "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    },
    dark: {
      background: "#020618",
      foreground: "#f8fafc",
      card: "#0f172b",
      "card-foreground": "#f8fafc",
      popover: "#0f172b",
      "popover-foreground": "#f8fafc",
      primary: "#e2e8f0",
      "primary-foreground": "#0f172b",
      secondary: "#1d293d",
      "secondary-foreground": "#f8fafc",
      muted: "#1d293d",
      "muted-foreground": "#90a1b9",
      accent: "#1d293d",
      "accent-foreground": "#f8fafc",
      destructive: "#ff6467",
      "destructive-foreground": "",
      border: "#ffffff",
      input: "#ffffff",
      ring: "#6a7282",
      "chart-1": "#1447e6",
      "chart-2": "#00bc7d",
      "chart-3": "#fe9a00",
      "chart-4": "#ad46ff",
      "chart-5": "#ff2056",
      radius: "",
      sidebar: "#0f172b",
      "sidebar-foreground": "#f8fafc",
      "sidebar-primary": "#1447e6",
      "sidebar-primary-foreground": "#f8fafc",
      "sidebar-accent": "#1d293d",
      "sidebar-accent-foreground": "#f8fafc",
      "sidebar-border": "#ffffff",
      "sidebar-ring": "#6a7282",
    },
  },
};
