import type { ThemePreset } from "../theme-types";

export const defaultViolet: ThemePreset = {
  label: "Default Violet",
  styles: {
    light: {
      background: "#ffffff",
      foreground: "#09090b",
      card: "#ffffff",
      "card-foreground": "#09090b",
      popover: "#ffffff",
      "popover-foreground": "#09090b",
      primary: "#8e51ff",
      "primary-foreground": "#f5f3ff",
      secondary: "#f4f4f5",
      "secondary-foreground": "#18181b",
      muted: "#f4f4f5",
      "muted-foreground": "#71717b",
      accent: "#f4f4f5",
      "accent-foreground": "#18181b",
      destructive: "#e7000b",
      "destructive-foreground": "",
      border: "#e4e4e7",
      input: "#e4e4e7",
      ring: "#8e51ff",
      "chart-1": "#f54900",
      "chart-2": "#009689",
      "chart-3": "#104e64",
      "chart-4": "#ffb900",
      "chart-5": "#fe9a00",
      radius: "0rem",
      sidebar: "#fafafa",
      "sidebar-foreground": "#09090b",
      "sidebar-primary": "#8e51ff",
      "sidebar-primary-foreground": "#f5f3ff",
      "sidebar-accent": "#f4f4f5",
      "sidebar-accent-foreground": "#18181b",
      "sidebar-border": "#e4e4e7",
      "sidebar-ring": "#8e51ff",
      "font-sans":
        "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      "font-serif":
        "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
      "font-mono":
        "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    },
    dark: {
      background: "#09090b",
      foreground: "#fafafa",
      card: "#18181b",
      "card-foreground": "#fafafa",
      popover: "#18181b",
      "popover-foreground": "#fafafa",
      primary: "#7f22fe",
      "primary-foreground": "#f5f3ff",
      secondary: "#27272a",
      "secondary-foreground": "#fafafa",
      muted: "#27272a",
      "muted-foreground": "#9f9fa9",
      accent: "#27272a",
      "accent-foreground": "#fafafa",
      destructive: "#ff6467",
      "destructive-foreground": "",
      border: "#ffffff",
      input: "#ffffff",
      ring: "#7f22fe",
      "chart-1": "#1447e6",
      "chart-2": "#00bc7d",
      "chart-3": "#fe9a00",
      "chart-4": "#ad46ff",
      "chart-5": "#ff2056",
      radius: "",
      sidebar: "#18181b",
      "sidebar-foreground": "#fafafa",
      "sidebar-primary": "#7f22fe",
      "sidebar-primary-foreground": "#f5f3ff",
      "sidebar-accent": "#27272a",
      "sidebar-accent-foreground": "#fafafa",
      "sidebar-border": "#ffffff",
      "sidebar-ring": "#7f22fe",
    },
  },
};
