import type { ThemePreset } from "../theme-types";

export const defaultStone: ThemePreset = {
  label: "Default Stone",
  styles: {
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#ffffff",
      "card-foreground": "#0a0a0a",
      popover: "#ffffff",
      "popover-foreground": "#0a0a0a",
      primary: "#171717",
      "primary-foreground": "#fafafa",
      secondary: "#f5f5f5",
      "secondary-foreground": "#171717",
      muted: "#f5f5f5",
      "muted-foreground": "#737373",
      accent: "#f5f5f5",
      "accent-foreground": "#171717",
      destructive: "#e7000b",
      "destructive-foreground": "",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#a1a1a1",
      "chart-1": "#f54900",
      "chart-2": "#009689",
      "chart-3": "#104e64",
      "chart-4": "#ffb900",
      "chart-5": "#fe9a00",
      radius: "0.625rem",
      sidebar: "#fafafa",
      "sidebar-foreground": "#0a0a0a",
      "sidebar-primary": "#171717",
      "sidebar-primary-foreground": "#fafafa",
      "sidebar-accent": "#f5f5f5",
      "sidebar-accent-foreground": "#171717",
      "sidebar-border": "#e5e5e5",
      "sidebar-ring": "#a1a1a1",
      "font-sans": "Inter, sans-serif",
      "font-serif": "Source Serif 4, serif",
      "font-mono": "JetBrains Mono, monospace",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#171717",
      "card-foreground": "#fafafa",
      popover: "#262626",
      "popover-foreground": "#fafafa",
      primary: "#e5e5e5",
      "primary-foreground": "#171717",
      secondary: "#262626",
      "secondary-foreground": "#fafafa",
      muted: "#262626",
      "muted-foreground": "#a1a1a1",
      accent: "#404040",
      "accent-foreground": "#fafafa",
      destructive: "#ff6467",
      "destructive-foreground": "",
      border: "#ffffff",
      input: "#ffffff",
      ring: "#737373",
      "chart-1": "#1447e6",
      "chart-2": "#00bc7d",
      "chart-3": "#fe9a00",
      "chart-4": "#ad46ff",
      "chart-5": "#ff2056",
      radius: "",
      sidebar: "#171717",
      "sidebar-foreground": "#fafafa",
      "sidebar-primary": "#1447e6",
      "sidebar-primary-foreground": "#fafafa",
      "sidebar-accent": "#262626",
      "sidebar-accent-foreground": "#fafafa",
      "sidebar-border": "#ffffff",
      "sidebar-ring": "#525252",
    },
  },
};
